// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCrE-8dQ9wiDWCf6nVCfaPISodKiYR_xg',
    appId: '1:428106498244:web:db4c35b78af614b87d8991',
    messagingSenderId: '428106498244',
    projectId: 'habita-app-269b7',
    authDomain: 'habita-app-269b7.firebaseapp.com',
    storageBucket: 'habita-app-269b7.firebasestorage.app',
    measurementId: 'G-3VNG85VQ7E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPwPOVs0gi4HRNCWKeUMOLS1C70kdgB4k',
    appId: '1:428106498244:android:c53203faa7aedc867d8991',
    messagingSenderId: '428106498244',
    projectId: 'habita-app-269b7',
    storageBucket: 'habita-app-269b7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnZmRok_LWEt9oDHQhO7DYJDJaGpw7DEQ',
    appId: '1:428106498244:ios:e6bd0a1b71fcb42b7d8991',
    messagingSenderId: '428106498244',
    projectId: 'habita-app-269b7',
    storageBucket: 'habita-app-269b7.firebasestorage.app',
    iosBundleId: 'com.example.habita',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnZmRok_LWEt9oDHQhO7DYJDJaGpw7DEQ',
    appId: '1:428106498244:ios:e6bd0a1b71fcb42b7d8991',
    messagingSenderId: '428106498244',
    projectId: 'habita-app-269b7',
    storageBucket: 'habita-app-269b7.firebasestorage.app',
    iosBundleId: 'com.example.habita',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCrE-8dQ9wiDWCf6nVCfaPISodKiYR_xg',
    appId: '1:428106498244:web:935fb6b7e3028ecc7d8991',
    messagingSenderId: '428106498244',
    projectId: 'habita-app-269b7',
    authDomain: 'habita-app-269b7.firebaseapp.com',
    storageBucket: 'habita-app-269b7.firebasestorage.app',
    measurementId: 'G-M70MJV9QC5',
  );
}
